language: csharp
solution: src/RunProcessAsTask.sln
script:
  - xbuild /p:Configuration=Release src/RunProcessAsTask.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./src/RunProcessAsTask/bin/Release/RunProcessAsTask.dll